### PR TITLE
2037 required definition

### PR DESCRIPTION
**Pull request by mrix**

### CODE REVIEW

**Comment by lapistano** [comment]
pls indicate in 'description' what is this PR about.

**Comment by hairmare** [comment]
Also, scrutinizer found some stuff worth checking...

**Comment by lapistano** [comment]
@mrix  erm .. closed without notice? 
Why?

**Comment by narcoticfresh** [comment]
@mrix your PR looks really valuable somehow, pls re-open it in some way.. i assume you want to define subproperties as required but not their parents or something like that? we just wanted a short description that helps us to know what the PR is about ;-)

**Comment by mrix** [comment]
@lapistano  I want to split this pull request into two separate.

**Pull request closed without merging**
