### PR TITLE
Add simple integration tests that exercises the dotted search feature

### PR DESCRIPTION
**Pull request by hairmare**

### CODE REVIEW

**Comment by hairmare** [comment]
This seems to work on travis with 5.6 (the errors with php7 are most likely unrelated to the changes). What I don't get is why this is failing locally, i probably need to cleanstart again.

**Comment by jacobchristensen79** [comment]
Just saw that the search is done on app/core, this has no text search indexes.

**Comment by hairmare** [comment]
It's on `/core/module/` and uses the `key` field which should have an index.

**Comment by hairmare** [comment]
replaced with #466

**Pull request closed without merging**
