### PR TITLE
extend put action of file service

### PR DESCRIPTION
**Pull request by samsamann**
* Now it's possible to update the content of a existing file.
* Implement new metadata (link.type and filename)

### CODE REVIEW

**Comment by hairmare** [comment]
Looks ok, waiting on scrutinizer...

**Comment by hairmare** [comment]
These both seem relevant: https://scrutinizer-ci.com/g/libgraviton/graviton/inspections/7ca13445-7d8b-43b0-8e53-b06508a895bc/issues/files/src/Graviton/FileBundle/Controller/FileController.php?status=new&orderField=path&order=asc

Most of the others seem to stem from me not doing proper review on a refactor in #157

**Comment by samsamann** [comment]
I'm not sure if the secound one is  a bug!
https://scrutinizer-ci.com/g/libgraviton/graviton/inspections/7ca13445-7d8b-43b0-8e53-b06508a895bc/issues/files/src/Graviton/FileBundle/Controller/FileController.php?status=new&orderField=path&order=asc
When the client does not set the accept header, it will return the file content! It's that correct?!

**Comment by hairmare** [comment]
Yeah we can ignore the second one, that is what we actually want...

**Pull request merged**
