### PR TITLE
small refactor on resource generator

### PR DESCRIPTION
**Pull request by hairmare**
Puts the field mapping code into its own ``mapField`` method and adds tests for the new method.

It also decouples ``ResourceGenerator`` from ``InputInterface`` by moving ``JsonDefinition`` creation to the calling command. This is a first step towards moving the definition creation towards the dic.

Also adds some todos for future refactor potential and cleans up some docs and hinting things.

### CODE REVIEW

**Comment by hairmare** [comment]
I fixed tests by activating ``E_ALL`` reporting due to the reason for the last error being a missing variable that would have been caught by ``E_STRICT``.

Also fixed the underlying issue that was introduced in a last minute refactor (a71886e).

@narcoticfresh could you point me in the direction of a json that should not get a controller? I'm having a hard time finding one to smoke-screen the no-controller option.

**Comment by narcoticfresh** [comment]
@hairmare An example would be 'CustomerContact.json' in the fi**ova (to avoid legal names) loadPackage (inherited in the s*kb-* packages). This has no service URI defined and thus should not have a controller.. Or Balance.json is another..

CustomerContact may change as soon as I merged a PR in Stash..

**Comment by hairmare** [comment]
Thanks for the examples, will look in the f\*ing F\* that s\* are using :trollface:

**Comment by hairmare** [comment]
I did some smoke-screening and everything seems to look ok now. Balance.json is not generating a Controller but, for instance, CustomerNote.json is generating one.

AFAIK this is the intended behaviour.

**Comment by narcoticfresh** [comment]
hm, something is quite wrong.. i checked it out on my wrapper, suddenly all the paths to the generated services changed.. ;-/

i.e. a have a url http://localhost:8000/financingmortgagecost/financingmortgagecost, which differs from the one defined in the json file..

so this doesn't work as expected anymore..

**Comment by narcoticfresh** [comment]
AND IMPORTANT: i have a service /balance/balance now - this one one (as we said) that shouldn't be generated as it hasn't have a service uri defined thus should not have a controller..

**Comment by hairmare** [comment]
This has been taken care of with #117 #118 #119.

**Pull request closed without merging**
