### PR TITLE
Introduce composer configure command for jenkins

### PR DESCRIPTION
**Pull request by hairmare**
After this we can make jenkins configure deploy-scripts in an empty workspace with ``composer configure``.

### CODE REVIEW

**Comment by hairmare** [comment]
The reason this is failing is fixed in #163 :rage2:

**Comment by narcoticfresh** [comment]
is it unfriendly if i merge #163 myself now? :rabbit:

**Comment by narcoticfresh** [comment]
@samsamann is nowhere to be found and it's a small PR..

**Comment by hairmare** [comment]
hit it :)

**Comment by hairmare** [comment]
I forgot: :rabbit2:

**Comment by narcoticfresh** [comment]
@hairmare ok; pls merge develop into this..

**Comment by hairmare** [comment]
rebased, waiting for ci again :rage3:

**Comment by narcoticfresh** [comment]
ooh, :rage4: is the highest rage level already? @github should add more :+1:

**Comment by hairmare** [comment]
back at :rage1:

:point_right:  :dancers: :rabbit: :dancer: :rabbit2:

**Pull request merged**
