### PR TITLE
finish /core/config service

### PR DESCRIPTION
**Pull request by hairmare**
Finishes the work @lapistano did on #101. It also adds some meaningful fixtures that look like the kind of data we would like in this service.

### CODE REVIEW

**Comment by lapistano** [comment]
see branch feature/GRV-1263, the current PR #107 does not reflect the acceptance criteria in complete .. 
btw. the verification is breaking my neck here ..

**Comment by hairmare** [comment]
Yeah, we won't be able to do "only existing app can be used" as of now. We need a story to create that as a real feature and it won't be easy.

Looking at the validation criteria in the story it seems we mis-estimated this badly. Maybe we should merge something like in this PR and crea backlog stories on the validation parts.

I looks as though there is still some low-level work to do there.

**Comment by lapistano** [comment]
yeah, I thought of doing this with this story, but you are probably right to extract this into another story.

**Comment by lapistano** [comment]
so we merge this am flush feature/GRV-1263?

**Comment by hairmare** [comment]
@lapistano If it's ok with you.

I've already started on the reference validation bit since that seems to be implementable using a customer validator. My work is on the [feature/app-ref-validation](https://github.com/libgraviton/graviton/tree/feature/app-ref-validation) branch.

**Comment by lapistano** [comment]
ok ... fine with me .. merging ...

**Pull request merged**
