### PR TITLE
fix swagger-ui notation

### PR DESCRIPTION
**Pull request by narcoticfresh**
sadly, composer doesn't detect changes made in a package purely referred as zip package.. i needed to delete the local package in order to update it - notating the source in the composer.json fixes that so every user gets updated swagger-ui..

### CODE REVIEW

**Comment by hairmare** [comment]
Can we remove the zipfile? Needs an update to composer.lock as well.

**Comment by narcoticfresh** [comment]
Fixed, so merge please..

**Comment by narcoticfresh** [comment]
WTF with travis? he doesn't find phpcs..(?)
@hairmare do you have any idea how this is possible?

**Comment by hairmare** [comment]
dafuq? Imma trigger a rebuild to check and look into it later if that doesn't help.

**Comment by hairmare** [comment]
I found the reason, this is a compat issue with me releasing a new graviton/codesniffer yesterday.

I'll document what to do as soon as we re from Grosi...

**Comment by hairmare** [comment]
If you switch libgraviton/codesniffer to 1.2 it should work again.

```
"libgraviton/codesniffer": "1.2.0"
```

**Comment by hairmare** [comment]
Sorry about this breaking change. You can either merge #18 or change this as shown.

**Comment by narcoticfresh** [comment]
i'll wait for #18 that @lapistano can merge..
this is all way too time consuming, i need to be able to work on the sprint stuff again..

**Comment by narcoticfresh** [comment]
@hairmare OK; travis says 'ok' passes after the merge..

**Comment by hairmare** [comment]
I'll merge it as soon as scrutinizer is through. It should get to green as well since the last merge :)

**Pull request merged**
