### PR TITLE
Make schema extendable

### PR DESCRIPTION
**Pull request by mrix**
This is needed to add "virtual" services:
* add any definitions file with `baseController`
* override schema/data methods in service controller

### CODE REVIEW

**Comment by hairmare** [comment]
@mrix Please clarify what user story this was written for.

**Comment by mrix** [comment]
At the moment declaring of key-indexed objects is not possible. I want to convert array field to object in controller.

Then I can add the definition:
```json
{
  "id": "SchemaExample",
  "service": {
    "readOnly": true,
    "routerBase": "/schema-example/",
    "baseController": "\\Test\\SchemaExampleController"
  },
  "target": {
    "fields": [
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "items.0.key",
        "type": "string"
      },
      {
        "name": "items.0.value",
        "type": "int"
      }
    ]
  }
}
```

and controller:
```php
class SchemaExampleController extends RestController
{
    /**
     * @inheritdoc
     */
    public function deleteAction($id)
    {
        throw new MethodNotAllowedHttpException(['GET']);
    }

    /**
     * @inheritdoc
     */
    public function putAction($id, Request $request)
    {
        throw new MethodNotAllowedHttpException(['GET']);
    }

    /**
     * @inheritdoc
     */
    public function postAction(Request $request)
    {
        throw new MethodNotAllowedHttpException(['GET']);
    }

    /**
     * @inheritdoc
     */
    public function allAction(Request $request)
    {
        throw new NotFoundException();
    }

    /**
     * @inheritdoc
     */
    public function getAction(Request $request, $id)
    {
        returmn parent::getAction(Request $request, $id);
    }

    /**
     * @inheritdoc
     */
    public function getModelSchema($modelName)
    {
        $schema = $this->getSchemaUtils()->getModelSchema($modelName, $this->getModel());

        $modules = $schema->getProperty('items');
        $modules->setType('object');
        $modules->setAdditionalProperties($modules->getItems());
        $modules->setItems(null);

        return $schema;
    }

    /**
     * @inheritdoc
     */
    public function getCollectionSchema($modelName)
    {
        $collectionSchema = new Schema();
        $collectionSchema->setTitle('List of items');
        $collectionSchema->setType('array');
        $collectionSchema->setItems($this->getModelSchema($modelName));
        return $collectionSchema;
    }

    /**
     * @inheritdoc
     */
    protected function findRecord($id)
    {
        $record = parent::findRecord($id);

        $items = array_reduce($record->getItems(), function ($result, SchemaExampleItem $item) {
            $result[$item->getKey()] = $item;
            return $result;
        }, []);
        $record->setItems($items);

        return $record;
    }
}
```

**Comment by hairmare** [comment]
I'm well aware of that, it's what I've been working on the past few days...

**Comment by lapistano** [comment]
duplicate work ... #closed

**Pull request closed without merging**
