### PR TITLE
1454 json definition schema

### PR DESCRIPTION
**Pull request by mrix**
* Added JSON schema for definition files
* Added JSON definitions validation
* Added console command to validate JSON definitions

This pull request depends on #231 because the `/file` service has invalid definition. Empty fixtures `{}` are transformed to `[]` during deserialization and serialization in generator command.

Todo
- [x] Extend schema with fields described in `errors.txt` (see information in JIRA issue)
- [x] Move JSON schema to https://github.com/libgraviton/json-schema/
- [x] Make Graviton take the JSON file from the new location
- [x] Optionally: Make https://github.com/libgraviton/json-schema/ also use the same bundle you use here - the one i tried to incorporate there to validate the schema itself doesn't pickup some errors it seems.

### CODE REVIEW

**Comment by lapistano** [comment]
@mrix  pls check tests and make them green before the review can start.

**Comment by mrix** [comment]
@lapistano This pull request depends on #231.
I have split this into two parts because #231 has no global changes and fixes a bug in serializer schema for `service.fixtures`. This pull request can break compatibility with some existing definitions, and further changes may be required to fix it. I have added detailed report about validation in JIRA.

Please check #231 first.

**Comment by narcoticfresh** [comment]
@mrix i merged #231, please merge develop again and see..

**Comment by mrix** [comment]
@narcoticfresh Done.

**Comment by narcoticfresh** [comment]
@mrix 
In GRV-1454 you rightly found more errors (`errors.txt`). Yes, please fix those - loader based JSON files have more properties then 'normal' loader definitions. I'll give you more details in JIRA..

Additionally, we already started a small project having the schema. The schema itself (only that!) should *not* be in Graviton, but externally so other components (like our loader) can get them easily.. See here -> https://github.com/libgraviton/json-schema/tree/feature/initial-json

**Comment by narcoticfresh** [comment]
@mrix i added some todos for you in this PRs description

**Comment by mrix** [comment]
Hi @narcoticfresh. I moved bundle with JSON schema to https://github.com/libgraviton/json-schema/pull/1. Or should I move JSON schema file only?

**Comment by mrix** [comment]
@narcoticfresh I've finished working on this.
Our [JSON schema](https://github.com/libgraviton/json-schema/blob/develop/src/Graviton/JsonSchemaBundle/Resources/schema/loadconfig/v1.0/schema.json) is not validated properly because my PR https://github.com/justinrainbow/json-schema/pull/186 is not merged yet. But validating JSON definitions is working fine.

**Comment by narcoticfresh** [comment]
@mrix it looks quite better.. 

two things
* i somehow don't see how and where the validator finds its schema file.. i see the param `%graviton.jsonschema.schema.uri%` - but i don't see where its set.. can u point me to that? 
* if i provoke a syntax error in a definition file, i get `[Graviton\JsonSchemaBundle\Validator\InvalidJsonException]  
  Malformed JSON: object value separator ',' expected `<br />That's good - but is there any way we can print out the file name path of the file where the error is located? Same as `HadesArchitect\JsonSchemaBundle\Exception\ViolationException` - I don't see which file has the error it prints..

**Comment by mrix** [comment]
@narcoticfresh 
1. https://github.com/libgraviton/json-schema/blob/develop/src/Graviton/JsonSchemaBundle/GravitonJsonSchemaBundle.php#L30
2. It is a difficult task because we have some different JSON loader strategies. And we pass raw JSON to `graviton:generate:bundle` command, when we generate bundles for embedded objects. You can use `graviton:validate:definition:directory` command to validate JSON files.

**Comment by narcoticfresh** [comment]
@mrix 
i think this is ready to merge. I'll do so once we have the next customer delivery out of the door..

i've tagged https://github.com/libgraviton/json-schema/releases/tag/v0.1.0 - please merge `develop`, change the composer.json `require` to this tagged release and re-update the dep.

**Comment by mrix** [comment]
@narcoticfresh JSON schema is broken. Please merge https://github.com/libgraviton/json-schema/pull/7

**Comment by narcoticfresh** [comment]
@mrix i merged libgraviton/json-schema#7 and tagged 0.3.0 there..

**Comment by narcoticfresh** [comment]
@mrix please set the dependency on `"graviton/json-schema": "dev-develop",` in composer.json to a tagged release, should be `"graviton/json-schema": "~0.3"` or something like that.. then rebump..

**Comment by mrix** [comment]
@narcoticfresh done.
I've rechecked existing definitions. All SZKB definitions in `develop` branch are valid.

**Pull request merged**
