### PR TITLE
Fix segfault in HHVM.

### PR DESCRIPTION
**Pull request by mrix**
Skipping test that is broken in HHVM.

### CODE REVIEW

**Comment by hairmare** [comment]
Why would we want to skip this? All skipping it accomplishes is that we ignore that our code fails on hhvm. If hhvm ever fixes such segfaults we won't notice that due to the tests still failing. 

If anything the segfault should get reported to hhvm directly. OTOH we don't really support hhvm and it was added to the build matrix out of pure curiosity.

**Comment by mrix** [comment]
@hairmare it is bug in HHVM. Other developers are doing [the same](https://github.com/symfony/symfony/search?q=defined+HHVM_VERSION).
I've already created an issue in HHVM tracker

**Comment by mrix** [comment]
See https://github.com/facebook/hhvm/issues/6168

**Comment by narcoticfresh** [comment]
@mrix 
I agree with @hairmare. HHVM is not critical for us, we just let it fail until - maybe some day - it will work as expected. In the issue you reference there is already a proposed fixing PR..

**Pull request closed without merging**
