### PR TITLE
47970 add elemmatch operator

### PR DESCRIPTION
**Pull request by mrix**
This is a part of [EVO-623](https://issue.swisscom.ch/browse/EVO-623). This is needed for searching files by links using `elemMatch()` RQL operator:
* Added new functional test
* Added `RqlFieldsCompilerPass` to save `rql field <=> database field` mapping
* Added `FieldNameSearchListener` to map RQL field names to correct database names
* Fixed a small bug in JSON definition parsing

This depends on the following changes:
* [x] https://github.com/libgraviton/php-rql-parser/pull/54
* [x] https://github.com/libgraviton/GravitonRqlParserBundle/pull/28
* [x] https://github.com/libgraviton/GravitonTestServicesBundle/pull/19
* [x] docs update gravity-platform/doc#18
* [x] reference evo number in pr description
* [x] update local `composer.*` files

I will remove aliases from `composer.json` when they will be merged.

### CODE REVIEW

**Comment by hairmare** [comment]
What does `elemMatch()` do?

**Comment by mrix** [comment]
`elemMatch()` RQL operator is the binding to [$elemMatch MongoDb operator](http://docs.mongodb.org/v2.2/reference/operator/query/elemMatch/).

**Comment by hairmare** [comment]
This will need some documentation in https://github.com/gravity-platform/doc/blob/develop/source/_pages/api/rql.md as well.

**Comment by mrix** [comment]
@hairmare I just created pull request with documentation https://github.com/gravity-platform/doc/pull/18

**Pull request merged**
