### PR TITLE
Update all the things with composer

### PR DESCRIPTION
**Pull request by hairmare**
* [x] update all the things to their most current state
* [x] fix resulting issues (small stuff with phpcs and phpunit mock behaviour)
* [x] update dependencies in composer.json to make dep graph smaller and allow faster updating in the future as well as during travis runs

### CODE REVIEW

**Comment by lapistano** [comment]
@hairmare  still valid?

**Comment by hairmare** [comment]
Not without a rebase that I won't be getting around to soon.

**Comment by hairmare** [comment]
I just rebased this...

**Comment by narcoticfresh** [comment]
@lapistano anything blocking this? can merge?

**Comment by hairmare** [comment]
I rebased and fixed this for the umpteenth time yesterday. It's an easy merge and all my wrapper tests have indicated that it works as intended. If this doesn't get merged I probably won't rebase it again and will opt to write a tech-dept story. I don't really get why this small change is not getting merged after more than a month and each delay actually makes this harder to test.

**Comment by narcoticfresh** [comment]
@hairmare totally agree.. no reason to wait..

@lapistano @jacobchristensen79 @tobster67 @clementedalmagro @gfellerleonard @PanteraLX @janfriedli 
can somebody pleeeeease merge??? ;-)

**Pull request merged**
