### PR TITLE
Can haz symfony 2.7

### PR DESCRIPTION
**Pull request by hairmare**
This bumps our symfony dep to version that was not EOLed more than a week ago...

### CODE REVIEW

**Comment by hairmare** [comment]
@narcoticfresh & @lapistano We should merge this soonish... Whatcha think?

**Comment by lapistano** [comment]
@hairmare d'accord .. I was already wondering how far this is.

**Comment by hairmare** [comment]
@lapistano The airbrake bundle was the only thing holding us back, but my prs over there got accepted and tagged into a release. Everything else has been fine for quite some time now.

**Comment by narcoticfresh** [comment]
@hairmare sure.. don't see why not if all is green

**Comment by hairmare** [comment]
It should in a couple of minutes...

**Comment by hairmare** [comment]
@narcoticfresh @narcoticfresh Le all is well...

Who wants to do the honors.

**Comment by narcoticfresh** [comment]
don't mind if i do..

**Pull request merged**
