### PR TITLE
add field 'order' to /core/app

### PR DESCRIPTION
**Pull request by narcoticfresh**
* add 'order' field to /core/app
* add new fixture for app 'tablet' - this is the one the /configuration/module fixtures will point to
* changed tests to reflect changes..

### CODE REVIEW

**Comment by narcoticfresh** [comment]
I'm not sure if 'tablet' is a so good choice.. but we need something to reflect our app "ev0j4", but name neutral (IMHO).. so 'tablet' is our first app that will contain modules..

**Comment by hairmare** [comment]
I'm OK with the order field but I don't see any value in you changes with the additional feature. It might have been better to just rename the "Hello World" fixture to "Tablet" if this is really needed.

The reason this really bothers me is that it is making the ``AppControllerTest`` longer without adding to what is covered by it.

I'm OK with merging, but we really need to start keeping test data used by external devs seperate from fixture data used for unit tests.

**Comment by narcoticfresh** [comment]
Yes, we need to seperate the fixtures somehow in the future..
Additonally, consumers will need 'explicit' test fixtures (brand and product names in apps and modules) which we can't or shouldn't put in github.. I'm unsure how we should address this..

**Comment by narcoticfresh** [comment]
Hm, I just see that both DELETE and PUT tests use the 'hello world' resource that would now become Tablet.. So all those tests new to work with the 'tablet' app.. is that OK?

**Comment by hairmare** [comment]
totes ok

**Pull request merged**
